import { StyleSheet } from "react-native";

export function createThemedStyles(colors) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
    },
    root: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      paddingHorizontal: 18,
      paddingTop: 12,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.bgAlt,
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 14,
    },
    brandTitle: {
      fontSize: 26,
      fontWeight: "800",
      color: colors.text,
    },
    brandSub: {
      marginTop: 4,
      fontSize: 10,
      letterSpacing: 1.8,
      textTransform: "uppercase",
      color: colors.muted,
    },
    headerActions: {
      alignItems: "flex-end",
      gap: 8,
    },
    headerChip: {
      paddingHorizontal: 16,
      paddingVertical: 9,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    headerChipText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "800",
    },
    iconChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    iconText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: "700",
    },
    scrollContent: {
      paddingHorizontal: 16,
      paddingTop: 18,
      paddingBottom: 120,
      gap: 16,
    },
    heroCard: {
      borderRadius: 30,
      padding: 22,
      backgroundColor: colors.hero,
      borderWidth: 1,
      borderColor: colors.glassLine,
      shadowColor: colors.shadow,
      shadowOpacity: 1,
      shadowRadius: 30,
      shadowOffset: { width: 0, height: 18 },
      elevation: 10,
    },
    heroTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 14,
    },
    heroEyebrow: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 1.6,
      textTransform: "uppercase",
      marginBottom: 8,
    },
    heroTitle: {
      color: colors.text,
      fontSize: 26,
      lineHeight: 32,
      fontWeight: "800",
      maxWidth: 260,
    },
    heroBadge: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.accentSoft,
      borderWidth: 1,
      borderColor: colors.border,
    },
    heroBadgeText: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: "800",
    },
    heroMetricRow: {
      flexDirection: "row",
      gap: 12,
      marginTop: 22,
    },
    heroMetric: {
      flex: 1,
      borderRadius: 20,
      padding: 16,
      backgroundColor: colors.surfaceSoft,
      borderWidth: 1,
      borderColor: colors.border,
    },
    heroMetricLabel: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: "700",
      marginBottom: 10,
    },
    heroMetricValue: {
      color: colors.text,
      fontSize: 20,
      fontWeight: "900",
    },
    card: {
      borderRadius: 28,
      padding: 20,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: 1,
      shadowRadius: 22,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
    cardTitleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 18,
    },
    cardTitle: {
      flex: 1,
      fontSize: 21,
      fontWeight: "800",
      color: colors.text,
    },
    karatRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      justifyContent: "flex-end",
    },
    inputGrid: {
      flexDirection: "row",
      gap: 12,
      marginBottom: 18,
    },
    segmentCard: {
      marginTop: 6,
      borderRadius: 20,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSoft,
      gap: 12,
    },
    segmentLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.muted,
    },
    segmentRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    rateTag: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "700",
      alignSelf: "center",
      backgroundColor: colors.accentSoft,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      overflow: "hidden",
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 6,
    },
    noteCard: {
      borderRadius: 20,
      padding: 16,
      backgroundColor: colors.surfaceSoft,
      borderWidth: 1,
      borderColor: colors.border,
    },
    noteText: {
      color: colors.muted,
      fontSize: 14,
      fontWeight: "600",
    },
    finalBlock: {
      marginTop: 16,
      paddingHorizontal: 18,
      paddingVertical: 20,
      borderRadius: 22,
      backgroundColor: colors.accentDeep,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      shadowColor: colors.glow,
      shadowOpacity: 1,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 12 },
      elevation: 10,
    },
    finalLabel: {
      color: "#dde9ff",
      fontSize: 13,
      textTransform: "uppercase",
      letterSpacing: 1.4,
      fontWeight: "700",
    },
    finalAmount: {
      color: "#ffffff",
      fontSize: 29,
      fontWeight: "900",
      textAlign: "right",
      flexShrink: 1,
    },
    actionRow: {
      flexDirection: "row",
      gap: 12,
      marginTop: 2,
    },
    primaryButton: {
      flex: 1,
      paddingVertical: 15,
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: "center",
      shadowColor: colors.shadow,
      shadowOpacity: 0.9,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 6,
    },
    primaryButtonText: {
      color: colors.text,
      fontSize: 15,
      fontWeight: "800",
    },
    secondaryButton: {
      flex: 1,
      paddingVertical: 15,
      borderRadius: 18,
      backgroundColor: colors.surfaceSoft,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: "center",
      shadowColor: colors.shadow,
      shadowOpacity: 0.9,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 6,
    },
    secondaryButtonText: {
      color: colors.accent,
      fontSize: 15,
      fontWeight: "800",
    },
    stickyBar: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 18,
      paddingVertical: 16,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.hero,
    },
    stickyMeta: {
      color: colors.accent,
      fontSize: 13,
      fontWeight: "800",
    },
    stickySub: {
      marginTop: 3,
      color: colors.muted,
      fontSize: 12,
      fontWeight: "600",
    },
    stickyPrice: {
      color: colors.accent,
      fontSize: 24,
      fontWeight: "900",
      flexShrink: 1,
      textAlign: "right",
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: "flex-end",
    },
    modalCard: {
      maxHeight: "80%",
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      backgroundColor: colors.surface,
      padding: 20,
      borderTopWidth: 1,
      borderColor: colors.border,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "800",
      color: colors.text,
    },
    modalClose: {
      color: colors.accent,
      fontSize: 14,
      fontWeight: "800",
    },
    emptyText: {
      color: colors.muted,
      fontSize: 14,
      textAlign: "center",
      paddingVertical: 18,
    },
    historyItem: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSoft,
      padding: 14,
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 10,
    },
    historyTitle: {
      color: colors.accent,
      fontSize: 14,
      fontWeight: "800",
    },
    historyTime: {
      color: colors.muted,
      fontSize: 12,
      marginTop: 4,
      fontWeight: "600",
    },
    historyRight: {
      alignItems: "flex-end",
      gap: 8,
    },
    historyPrice: {
      color: colors.text,
      fontSize: 15,
      fontWeight: "800",
      textAlign: "right",
    },
    deleteText: {
      color: colors.red,
      fontSize: 12,
      fontWeight: "800",
    },
    clearButton: {
      marginTop: 12,
      paddingVertical: 14,
      borderRadius: 14,
      alignItems: "center",
      backgroundColor: colors.bgAlt,
      borderWidth: 1,
      borderColor: colors.border,
    },
    clearButtonText: {
      color: colors.red,
      fontSize: 14,
      fontWeight: "800",
    },
  });
}
