import { StyleSheet } from "react-native";

export function createThemedStyles(colors) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
    },
    root: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    header: {
      paddingHorizontal: 18,
      paddingTop: 12,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.bgAlt,
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 14,
      overflow: "visible",
      zIndex: 30,
    },
    brandTitle: {
      fontSize: 26,
      fontWeight: "800",
      color: colors.text,
    },
    brandSub: {
      marginTop: 4,
      fontSize: 10,
      letterSpacing: 1.8,
      textTransform: "uppercase",
      color: colors.muted,
    },
    headerMenuWrap: {
      alignItems: "flex-end",
      position: "relative",
      zIndex: 40,
    },
    menuButton: {
      width: 48,
      minHeight: 48,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.shadow,
      shadowOpacity: 0.8,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 5,
    },
    menuButtonIcon: {
      color: colors.accent,
      fontSize: 24,
      lineHeight: 24,
      fontWeight: "800",
      marginTop: -2,
    },
    menuDropdown: {
      position: "absolute",
      top: 56,
      right: 0,
      minWidth: 220,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.hero,
      padding: 10,
      gap: 6,
      shadowColor: colors.shadow,
      shadowOpacity: 1,
      shadowRadius: 22,
      shadowOffset: { width: 0, height: 12 },
      elevation: 10,
      zIndex: 20,
      overflow: "visible",
    },
    menuItem: {
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: colors.surfaceSoft,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 4,
    },
    menuItemTitle: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "800",
    },
    menuItemMeta: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: "600",
    },
    scrollContent: {
      paddingHorizontal: 16,
      paddingTop: 18,
      paddingBottom: 150,
      gap: 16,
    },
    heroCard: {
      borderRadius: 30,
      padding: 22,
      backgroundColor: colors.hero,
      borderWidth: 1,
      borderColor: colors.glassLine,
      shadowColor: colors.shadow,
      shadowOpacity: 1,
      shadowRadius: 30,
      shadowOffset: { width: 0, height: 18 },
      elevation: 10,
    },
    heroTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 14,
    },
    heroEyebrow: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 1.6,
      textTransform: "uppercase",
      marginBottom: 8,
    },
    heroTitle: {
      color: colors.text,
      fontSize: 26,
      lineHeight: 32,
      fontWeight: "800",
      maxWidth: 260,
    },
    heroBadge: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: colors.accentSoft,
      borderWidth: 1,
      borderColor: colors.border,
    },
    heroBadgeText: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: "800",
    },
    heroMetricRow: {
      flexDirection: "row",
      gap: 12,
      marginTop: 22,
    },
    heroMetric: {
      flex: 1,
      borderRadius: 20,
      padding: 16,
      backgroundColor: colors.surfaceSoft,
      borderWidth: 1,
      borderColor: colors.border,
    },
    heroMetricLabel: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: "700",
      marginBottom: 10,
    },
    heroMetricValue: {
      color: colors.text,
      fontSize: 20,
      fontWeight: "900",
    },
    card: {
      borderRadius: 28,
      padding: 20,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOpacity: 1,
      shadowRadius: 22,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
    cardTitleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 18,
    },
    cardTitle: {
      flex: 1,
      fontSize: 21,
      fontWeight: "800",
      color: colors.text,
    },
    karatRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      justifyContent: "flex-end",
    },
    inputGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
      marginBottom: 18,
    },
    segmentCard: {
      marginTop: 6,
      borderRadius: 20,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSoft,
      gap: 12,
    },
    segmentLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.muted,
    },
    segmentRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      width: "100%",
    },
    rateTag: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "700",
      alignSelf: "center",
      backgroundColor: colors.accentSoft,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      overflow: "hidden",
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 6,
    },
    noteCard: {
      borderRadius: 20,
      padding: 16,
      backgroundColor: colors.surfaceSoft,
      borderWidth: 1,
      borderColor: colors.border,
    },
    noteText: {
      color: colors.muted,
      fontSize: 14,
      fontWeight: "600",
    },
    finalBlock: {
      marginTop: 16,
      paddingHorizontal: 18,
      paddingVertical: 20,
      borderRadius: 22,
      backgroundColor: colors.accentDeep,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      shadowColor: colors.glow,
      shadowOpacity: 1,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 12 },
      elevation: 10,
    },
    finalLabel: {
      color: "#dde9ff",
      fontSize: 13,
      textTransform: "uppercase",
      letterSpacing: 1.4,
      fontWeight: "700",
    },
    finalAmount: {
      color: "#ffffff",
      fontSize: 29,
      fontWeight: "900",
      textAlign: "right",
      flexShrink: 1,
    },
    actionRow: {
      flexDirection: "row",
      gap: 12,
      marginTop: 2,
    },
    bottomOverlaySpacer: {
      height: 150,
    },
    primaryButton: {
      flex: 1,
      paddingVertical: 15,
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: "center",
      shadowColor: colors.shadow,
      shadowOpacity: 0.9,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 6,
    },
    primaryButtonText: {
      color: colors.text,
      fontSize: 15,
      fontWeight: "800",
    },
    secondaryButton: {
      flex: 1,
      paddingVertical: 15,
      borderRadius: 18,
      backgroundColor: colors.surfaceSoft,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: "center",
      shadowColor: colors.shadow,
      shadowOpacity: 0.9,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 6,
    },
    secondaryButtonText: {
      color: colors.accent,
      fontSize: 15,
      fontWeight: "800",
    },
    stickyBar: {
      position: "absolute",
      left: 14,
      right: 14,
      bottom: 92,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 18,
      paddingVertical: 14,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 22,
      backgroundColor: colors.hero,
      shadowColor: colors.shadow,
      shadowOpacity: 1,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 10,
    },
    stickyMeta: {
      color: colors.accent,
      fontSize: 13,
      fontWeight: "800",
    },
    stickySub: {
      marginTop: 3,
      color: colors.muted,
      fontSize: 12,
      fontWeight: "600",
    },
    stickyPrice: {
      color: colors.accent,
      fontSize: 22,
      fontWeight: "900",
      flexShrink: 1,
      textAlign: "right",
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: "flex-end",
    },
    modalCard: {
      maxHeight: "80%",
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      backgroundColor: colors.surface,
      padding: 20,
      borderTopWidth: 1,
      borderColor: colors.border,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "800",
      color: colors.text,
    },
    modalClose: {
      color: colors.accent,
      fontSize: 14,
      fontWeight: "800",
    },
    emptyText: {
      color: colors.muted,
      fontSize: 14,
      textAlign: "center",
      paddingVertical: 18,
    },
    historyItem: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceSoft,
      padding: 14,
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 10,
    },
    historyTitle: {
      color: colors.accent,
      fontSize: 14,
      fontWeight: "800",
    },
    historyTime: {
      color: colors.muted,
      fontSize: 12,
      marginTop: 4,
      fontWeight: "600",
    },
    historyRight: {
      alignItems: "flex-end",
      gap: 8,
    },
    historyPrice: {
      color: colors.text,
      fontSize: 15,
      fontWeight: "800",
      textAlign: "right",
    },
    deleteText: {
      color: colors.red,
      fontSize: 12,
      fontWeight: "800",
    },
    clearButton: {
      marginTop: 12,
      paddingVertical: 14,
      borderRadius: 14,
      alignItems: "center",
      backgroundColor: colors.bgAlt,
      borderWidth: 1,
      borderColor: colors.border,
    },
    clearButtonText: {
      color: colors.red,
      fontSize: 14,
      fontWeight: "800",
    },
    bottomNav: {
      position: "absolute",
      left: 14,
      right: 14,
      bottom: 12,
      minHeight: 68,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.hero,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
      paddingHorizontal: 10,
      paddingVertical: 8,
      shadowColor: colors.shadow,
      shadowOpacity: 1,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 12,
    },
    bottomNavItem: {
      flex: 1,
      minHeight: 52,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      marginHorizontal: 4,
      paddingHorizontal: 6,
    },
    bottomNavIcon: {
      fontSize: 15,
      fontWeight: "900",
      lineHeight: 18,
      marginBottom: 2,
    },
    bottomNavText: {
      fontSize: 12,
      fontWeight: "800",
      textAlign: "center",
    },
    interestContent: {
      paddingHorizontal: 16,
      paddingTop: 18,
      paddingBottom: 110,
      gap: 16,
    },
    interestHeader: {
      borderRadius: 28,
      padding: 22,
      backgroundColor: colors.hero,
      borderWidth: 1,
      borderColor: colors.glassLine,
    },
    interestTitle: {
      color: colors.text,
      fontSize: 28,
      lineHeight: 34,
      fontWeight: "900",
    },
    interestSubtitle: {
      color: colors.muted,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: "600",
      marginTop: 8,
    },
    radioGroup: {
      gap: 12,
    },
    radioItem: {
      minHeight: 44,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    radioOuter: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      alignItems: "center",
      justifyContent: "center",
    },
    radioInner: {
      width: 10,
      height: 10,
      borderRadius: 5,
    },
    radioLabel: {
      fontSize: 15,
      fontWeight: "700",
    },
    interestToggle: {
      minHeight: 42,
      borderRadius: 14,
      borderWidth: 1,
      paddingHorizontal: 13,
      paddingVertical: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    interestToggleText: {
      fontSize: 12,
      fontWeight: "800",
    },
    compoundBlock: {
      marginTop: 16,
      gap: 10,
    },
    compoundLabel: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    interestInputGroup: {
      gap: 8,
      marginTop: 12,
    },
    interestInputGroupInline: {
      flex: 1,
      minWidth: 180,
      gap: 8,
      marginTop: 12,
    },
    interestInput: {
      width: "100%",
      minHeight: 52,
      borderWidth: 1.5,
      borderRadius: 14,
      paddingHorizontal: 12,
      fontSize: 16,
      fontWeight: "700",
      outlineWidth: 0,
      outlineStyle: "none",
    },
    interestError: {
      color: colors.red,
      fontSize: 13,
      fontWeight: "800",
      textAlign: "center",
    },
    interestResultCard: {
      borderRadius: 28,
      padding: 20,
      backgroundColor: colors.resultSurface,
      borderWidth: 1,
      borderColor: colors.resultBorder,
      gap: 12,
      shadowColor: colors.shadow,
      shadowOpacity: 1,
      shadowRadius: 22,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
    resultEyebrow: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1.2,
    },
    resultAmount: {
      color: colors.resultText,
      fontSize: 32,
      fontWeight: "900",
    },
    interestResultRow: {
      minHeight: 34,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      borderTopWidth: 1,
      borderTopColor: colors.resultBorder,
      paddingTop: 10,
    },
    interestResultLabel: {
      color: colors.resultMuted,
      fontSize: 13,
      fontWeight: "700",
      flex: 1,
    },
    interestResultValue: {
      color: colors.resultText,
      fontSize: 14,
      fontWeight: "900",
      textAlign: "right",
      flex: 1,
    },
  });
}
